"""phase 11: group module

Revision ID: 008a97494325
Revises: eab65c7a4ca8
Create Date: 2026-05-01 11:00:07.578849
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '008a97494325'
down_revision: str | Sequence[str] | None = 'eab65c7a4ca8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_matrix',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'document_type', name='uq_approval_matrix_doc'),
    schema='grp'
    )
    op.create_table('compliance_item',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('compliance_type', sa.String(length=40), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('submitted_by', sa.BigInteger(), nullable=True),
    sa.Column('reference_number', sa.String(length=80), nullable=True),
    sa.Column('amount_filed', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_compliance_item_company_id'), 'compliance_item', ['company_id'], unique=False, schema='grp')
    op.create_index(op.f('ix_grp_compliance_item_compliance_type'), 'compliance_item', ['compliance_type'], unique=False, schema='grp')
    op.create_index(op.f('ix_grp_compliance_item_due_date'), 'compliance_item', ['due_date'], unique=False, schema='grp')
    op.create_index(op.f('ix_grp_compliance_item_state'), 'compliance_item', ['state'], unique=False, schema='grp')
    op.create_table('group_kpi_snapshot',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'metric', 'period_start', name='uq_group_kpi_window'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_group_kpi_snapshot_company_id'), 'group_kpi_snapshot', ['company_id'], unique=False, schema='grp')
    op.create_index(op.f('ix_grp_group_kpi_snapshot_metric'), 'group_kpi_snapshot', ['metric'], unique=False, schema='grp')
    op.create_table('intercompany_loan',
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('lender_company_id', sa.BigInteger(), nullable=False),
    sa.Column('borrower_company_id', sa.BigInteger(), nullable=False),
    sa.Column('principal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('interest_rate_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('settled_date', sa.Date(), nullable=True),
    sa.Column('outstanding_balance', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['borrower_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lender_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_intercompany_loan_ref'), 'intercompany_loan', ['ref'], unique=True, schema='grp')
    op.create_index(op.f('ix_grp_intercompany_loan_state'), 'intercompany_loan', ['state'], unique=False, schema='grp')
    op.create_table('inventory_pool',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_company_id', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='grp'
    )
    op.create_table('tax_group',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('representative_company_id', sa.BigInteger(), nullable=False),
    sa.Column('tax_authority_id', sa.String(length=40), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['representative_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='grp'
    )
    op.create_table('approval_matrix_rule',
    sa.Column('matrix_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('approver_user_id', sa.BigInteger(), nullable=True),
    sa.Column('approver_group_id', sa.BigInteger(), nullable=True),
    sa.Column('requires_n_approvers', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['approver_group_id'], ['core.group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approver_user_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matrix_id'], ['grp.approval_matrix.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='grp'
    )
    op.create_table('cost_allocation',
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('paying_company_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('basis', sa.String(length=20), nullable=False),
    sa.Column('expense_account_id', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounting.account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paying_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_cost_allocation_ref'), 'cost_allocation', ['ref'], unique=True, schema='grp')
    op.create_index(op.f('ix_grp_cost_allocation_state'), 'cost_allocation', ['state'], unique=False, schema='grp')
    op.create_table('inventory_pool_member',
    sa.Column('pool_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('transfer_cost_per_km', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pool_id'], ['grp.inventory_pool.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['wms.warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'warehouse_id', name='uq_pool_member'),
    schema='grp'
    )
    op.create_table('inventory_pool_rule',
    sa.Column('pool_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.BigInteger(), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('min_qty_threshold', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pool_id'], ['grp.inventory_pool.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['wms.product_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='grp'
    )
    op.create_table('loan_installment',
    sa.Column('loan_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['grp.intercompany_loan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='grp'
    )
    op.create_table('tax_group_member',
    sa.Column('tax_group_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.Column('left_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_group_id'], ['grp.tax_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_group_id', 'company_id', name='uq_tax_group_member'),
    schema='grp'
    )
    op.create_table('cost_allocation_line',
    sa.Column('allocation_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['grp.cost_allocation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id', 'company_id', name='uq_alloc_company'),
    schema='grp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_allocation_line', schema='grp')
    op.drop_table('tax_group_member', schema='grp')
    op.drop_table('loan_installment', schema='grp')
    op.drop_table('inventory_pool_rule', schema='grp')
    op.drop_table('inventory_pool_member', schema='grp')
    op.drop_index(op.f('ix_grp_cost_allocation_state'), table_name='cost_allocation', schema='grp')
    op.drop_index(op.f('ix_grp_cost_allocation_ref'), table_name='cost_allocation', schema='grp')
    op.drop_table('cost_allocation', schema='grp')
    op.drop_table('approval_matrix_rule', schema='grp')
    op.drop_table('tax_group', schema='grp')
    op.drop_table('inventory_pool', schema='grp')
    op.drop_index(op.f('ix_grp_intercompany_loan_state'), table_name='intercompany_loan', schema='grp')
    op.drop_index(op.f('ix_grp_intercompany_loan_ref'), table_name='intercompany_loan', schema='grp')
    op.drop_table('intercompany_loan', schema='grp')
    op.drop_index(op.f('ix_grp_group_kpi_snapshot_metric'), table_name='group_kpi_snapshot', schema='grp')
    op.drop_index(op.f('ix_grp_group_kpi_snapshot_company_id'), table_name='group_kpi_snapshot', schema='grp')
    op.drop_table('group_kpi_snapshot', schema='grp')
    op.drop_index(op.f('ix_grp_compliance_item_state'), table_name='compliance_item', schema='grp')
    op.drop_index(op.f('ix_grp_compliance_item_due_date'), table_name='compliance_item', schema='grp')
    op.drop_index(op.f('ix_grp_compliance_item_compliance_type'), table_name='compliance_item', schema='grp')
    op.drop_index(op.f('ix_grp_compliance_item_company_id'), table_name='compliance_item', schema='grp')
    op.drop_table('compliance_item', schema='grp')
    op.drop_table('approval_matrix', schema='grp')
    # ### end Alembic commands ###
