"""phase 14 thai compliance: SSO PND OT leave transfer + VAT WHT cert fixed-asset depreciation FX

Revision ID: 0ab6b3324dc8
Revises: 6412e294d058
Create Date: 2026-05-01 18:57:13.096631
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0ab6b3324dc8'
down_revision: str | Sequence[str] | None = '6412e294d058'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vat_period',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('output_vat', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('input_vat', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net_payable', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('credit_carried_forward', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.BigInteger(), nullable=True),
    sa.Column('rd_receipt_number', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_year', 'period_month', name='uq_vat_period'),
    schema='accounting'
    )
    op.create_index(op.f('ix_accounting_vat_period_company_id'), 'vat_period', ['company_id'], unique=False, schema='accounting')
    op.create_index(op.f('ix_accounting_vat_period_state'), 'vat_period', ['state'], unique=False, schema='accounting')
    op.create_table('pnd_filing',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('filing_type', sa.String(length=20), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('total_gross_wage', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_wht', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.BigInteger(), nullable=True),
    sa.Column('rd_receipt_number', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'filing_type', 'period_year', 'period_month', name='uq_pnd_filing_period'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_pnd_filing_company_id'), 'pnd_filing', ['company_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_pnd_filing_state'), 'pnd_filing', ['state'], unique=False, schema='hr')
    op.create_table('vat_line',
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=False),
    sa.Column('counterparty_tax_id', sa.String(length=40), nullable=True),
    sa.Column('invoice_number', sa.String(length=80), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('source_model', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['accounting.vat_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='accounting'
    )
    op.create_index(op.f('ix_accounting_vat_line_period_id'), 'vat_line', ['period_id'], unique=False, schema='accounting')
    op.create_table('fixed_asset',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('salvage_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('depreciation_method', sa.String(length=30), nullable=False),
    sa.Column('useful_life_months', sa.Integer(), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('book_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('asset_account_id', sa.BigInteger(), nullable=True),
    sa.Column('accumulated_depreciation_account_id', sa.BigInteger(), nullable=True),
    sa.Column('depreciation_expense_account_id', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('custodian_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_proceeds', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['accumulated_depreciation_account_id'], ['accounting.account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_account_id'], ['accounting.account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['custodian_employee_id'], ['hr.employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['depreciation_expense_account_id'], ['accounting.account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_code'),
    schema='accounting'
    )
    op.create_index(op.f('ix_accounting_fixed_asset_company_id'), 'fixed_asset', ['company_id'], unique=False, schema='accounting')
    op.create_index(op.f('ix_accounting_fixed_asset_state'), 'fixed_asset', ['state'], unique=False, schema='accounting')
    op.create_table('employee_transfer',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('from_company_id', sa.BigInteger(), nullable=False),
    sa.Column('to_company_id', sa.BigInteger(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('new_position', sa.String(length=120), nullable=True),
    sa.Column('new_department_id', sa.BigInteger(), nullable=True),
    sa.Column('new_warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('salary_adjustment_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('keep_service_date', sa.Boolean(), nullable=False),
    sa.Column('keep_leave_balance', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['new_department_id'], ['hr.department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_warehouse_id'], ['wms.warehouse.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_employee_transfer_employee_id'), 'employee_transfer', ['employee_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_employee_transfer_state'), 'employee_transfer', ['state'], unique=False, schema='hr')
    op.create_table('leave_entitlement',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('leave_type_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('granted_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carried_over', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('remaining_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['hr.leave_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'leave_type_id', name='uq_leave_entitlement'),
    schema='hr'
    )
    op.create_table('overtime_record',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('ot_kind', sa.String(length=30), nullable=False),
    sa.Column('hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('base_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate_multiplier', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_overtime_record_company_id'), 'overtime_record', ['company_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_overtime_record_employee_id'), 'overtime_record', ['employee_id'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_overtime_record_state'), 'overtime_record', ['state'], unique=False, schema='hr')
    op.create_index(op.f('ix_hr_overtime_record_work_date'), 'overtime_record', ['work_date'], unique=False, schema='hr')
    op.create_table('pnd_filing_line',
    sa.Column('filing_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('gross_wage', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wht_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wht_rate_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employee.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['filing_id'], ['hr.pnd_filing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_pnd_filing_line_filing_id'), 'pnd_filing_line', ['filing_id'], unique=False, schema='hr')
    op.create_table('sso_contribution',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('gross_wage', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('employee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('employer_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'period_year', 'period_month', name='uq_sso_contrib_period'),
    schema='hr'
    )
    op.create_table('sso_registration',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('ssn', sa.String(length=20), nullable=False),
    sa.Column('registered_date', sa.Date(), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=True),
    sa.Column('insured_type', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['hr.employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', name='uq_sso_employee'),
    sa.UniqueConstraint('ssn'),
    schema='hr'
    )
    op.create_index(op.f('ix_hr_sso_registration_employee_id'), 'sso_registration', ['employee_id'], unique=False, schema='hr')
    op.create_table('depreciation_entry',
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('depreciation_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('accumulated_to_date', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('book_value_after', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['accounting.fixed_asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['accounting.journal_entry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'period_year', 'period_month', name='uq_dep_entry_period'),
    schema='accounting'
    )
    op.create_index(op.f('ix_accounting_depreciation_entry_asset_id'), 'depreciation_entry', ['asset_id'], unique=False, schema='accounting')
    op.create_table('fx_revaluation',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_end_rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('booked_balance_fc', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('booked_balance_thb', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('revalued_balance_thb', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fx_gain_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['accounting.journal_entry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'currency', 'period_year', 'period_month', name='uq_fx_revaluation'),
    schema='accounting'
    )
    op.create_index(op.f('ix_accounting_fx_revaluation_company_id'), 'fx_revaluation', ['company_id'], unique=False, schema='accounting')
    op.create_table('wht_certificate',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('form_type', sa.String(length=10), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('payee_name', sa.String(length=255), nullable=False),
    sa.Column('payee_tax_id', sa.String(length=40), nullable=False),
    sa.Column('payee_address', sa.Text(), nullable=True),
    sa.Column('income_type_code', sa.String(length=10), nullable=False),
    sa.Column('income_description', sa.String(length=255), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wht_rate_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('wht_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['accounting.journal_entry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'form_type', 'period_year', 'sequence_number', name='uq_wht_cert_seq'),
    schema='accounting'
    )
    op.create_index(op.f('ix_accounting_wht_certificate_company_id'), 'wht_certificate', ['company_id'], unique=False, schema='accounting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounting_wht_certificate_company_id'), table_name='wht_certificate', schema='accounting')
    op.drop_table('wht_certificate', schema='accounting')
    op.drop_index(op.f('ix_accounting_fx_revaluation_company_id'), table_name='fx_revaluation', schema='accounting')
    op.drop_table('fx_revaluation', schema='accounting')
    op.drop_index(op.f('ix_accounting_depreciation_entry_asset_id'), table_name='depreciation_entry', schema='accounting')
    op.drop_table('depreciation_entry', schema='accounting')
    op.drop_index(op.f('ix_hr_sso_registration_employee_id'), table_name='sso_registration', schema='hr')
    op.drop_table('sso_registration', schema='hr')
    op.drop_table('sso_contribution', schema='hr')
    op.drop_index(op.f('ix_hr_pnd_filing_line_filing_id'), table_name='pnd_filing_line', schema='hr')
    op.drop_table('pnd_filing_line', schema='hr')
    op.drop_index(op.f('ix_hr_overtime_record_work_date'), table_name='overtime_record', schema='hr')
    op.drop_index(op.f('ix_hr_overtime_record_state'), table_name='overtime_record', schema='hr')
    op.drop_index(op.f('ix_hr_overtime_record_employee_id'), table_name='overtime_record', schema='hr')
    op.drop_index(op.f('ix_hr_overtime_record_company_id'), table_name='overtime_record', schema='hr')
    op.drop_table('overtime_record', schema='hr')
    op.drop_table('leave_entitlement', schema='hr')
    op.drop_index(op.f('ix_hr_employee_transfer_state'), table_name='employee_transfer', schema='hr')
    op.drop_index(op.f('ix_hr_employee_transfer_employee_id'), table_name='employee_transfer', schema='hr')
    op.drop_table('employee_transfer', schema='hr')
    op.drop_index(op.f('ix_accounting_fixed_asset_state'), table_name='fixed_asset', schema='accounting')
    op.drop_index(op.f('ix_accounting_fixed_asset_company_id'), table_name='fixed_asset', schema='accounting')
    op.drop_table('fixed_asset', schema='accounting')
    op.drop_index(op.f('ix_accounting_vat_line_period_id'), table_name='vat_line', schema='accounting')
    op.drop_table('vat_line', schema='accounting')
    op.drop_index(op.f('ix_hr_pnd_filing_state'), table_name='pnd_filing', schema='hr')
    op.drop_index(op.f('ix_hr_pnd_filing_company_id'), table_name='pnd_filing', schema='hr')
    op.drop_table('pnd_filing', schema='hr')
    op.drop_index(op.f('ix_accounting_vat_period_state'), table_name='vat_period', schema='accounting')
    op.drop_index(op.f('ix_accounting_vat_period_company_id'), table_name='vat_period', schema='accounting')
    op.drop_table('vat_period', schema='accounting')
    # ### end Alembic commands ###
