"""phase 9 multi-company + locale

Revision ID: 5ecd11f789ab
Revises: c423734f6afb
Create Date: 2026-04-30 16:39:24.395701
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5ecd11f789ab'
down_revision: str | Sequence[str] | None = 'c423734f6afb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['core.company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='core'
    )
    op.create_table('user_company',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id'),
    schema='core'
    )
    op.add_column('user', sa.Column('default_company_id', sa.BigInteger(), nullable=True), schema='core')
    op.add_column(
        'user',
        sa.Column('preferred_locale', sa.String(length=8), server_default='th-TH', nullable=False),
        schema='core',
    )
    op.create_foreign_key('fk_user_default_company', 'user', 'company', ['default_company_id'], ['id'], source_schema='core', referent_schema='core', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_department_manager', 'department', 'employee', ['manager_id'], ['id'], source_schema='hr', referent_schema='hr', ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_department_manager', 'department', schema='hr', type_='foreignkey')
    op.drop_constraint('fk_user_default_company', 'user', schema='core', type_='foreignkey')
    op.drop_column('user', 'preferred_locale', schema='core')
    op.drop_column('user', 'default_company_id', schema='core')
    op.drop_table('user_company', schema='core')
    op.drop_table('company', schema='core')
    # ### end Alembic commands ###
