"""phase 12: group extras (xc-customer/vendor, rebate, cash pool, sku bridge, brand license, transfer pricing, approval substitution)

Revision ID: 6412e294d058
Revises: 008a97494325
Create Date: 2026-05-01 11:11:19.027389
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6412e294d058'
down_revision: str | Sequence[str] | None = '008a97494325'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_substitution',
    sa.Column('primary_user_id', sa.BigInteger(), nullable=False),
    sa.Column('fallback_user_id', sa.BigInteger(), nullable=False),
    sa.Column('primary_company_id', sa.BigInteger(), nullable=True),
    sa.Column('document_type', sa.String(length=40), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fallback_user_id'], ['core.user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_company_id'], ['core.company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_user_id'], ['core.user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_user_id', 'valid_from', name='uq_approval_substitution'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_approval_substitution_primary_user_id'), 'approval_substitution', ['primary_user_id'], unique=False, schema='grp')
    op.create_table('bank_account',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.Column('account_number', sa.String(length=40), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'account_number', name='uq_bank_account'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_bank_account_company_id'), 'bank_account', ['company_id'], unique=False, schema='grp')
    op.create_table('brand_license',
    sa.Column('brand_code', sa.String(length=40), nullable=False),
    sa.Column('brand_name', sa.String(length=120), nullable=False),
    sa.Column('owner_company_id', sa.BigInteger(), nullable=False),
    sa.Column('licensed_to_company_id', sa.BigInteger(), nullable=False),
    sa.Column('territory', sa.String(length=80), nullable=False),
    sa.Column('license_scope', sa.String(length=20), nullable=False),
    sa.Column('royalty_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('minimum_royalty_per_period', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('period_kind', sa.String(length=20), nullable=False),
    sa.Column('product_category_ids', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['licensed_to_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_code', 'licensed_to_company_id', 'valid_from', name='uq_brand_license_window'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_brand_license_brand_code'), 'brand_license', ['brand_code'], unique=False, schema='grp')
    op.create_table('cash_forecast_snapshot',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_in', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_out', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('projected_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('risk_flag', sa.String(length=20), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'forecast_date', 'horizon_days', name='uq_cash_forecast'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_cash_forecast_snapshot_company_id'), 'cash_forecast_snapshot', ['company_id'], unique=False, schema='grp')
    op.create_index(op.f('ix_grp_cash_forecast_snapshot_forecast_date'), 'cash_forecast_snapshot', ['forecast_date'], unique=False, schema='grp')
    op.create_table('cash_pool',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_company_id', sa.BigInteger(), nullable=False),
    sa.Column('target_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('sweep_threshold_pct', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='grp'
    )
    op.create_table('cross_company_customer',
    sa.Column('group_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('primary_phone', sa.String(length=40), nullable=True),
    sa.Column('customer_group', sa.String(length=20), nullable=False),
    sa.Column('group_credit_limit', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('group_credit_consumed', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('group_ltv_score', sa.Float(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code'),
    schema='grp'
    )
    op.create_table('cross_company_vendor',
    sa.Column('group_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=True),
    sa.Column('primary_phone', sa.String(length=40), nullable=True),
    sa.Column('payment_currency', sa.String(length=10), nullable=False),
    sa.Column('lifetime_spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ytd_spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('group_otd_pct', sa.Float(), nullable=False),
    sa.Column('group_quality_pct', sa.Float(), nullable=False),
    sa.Column('group_score', sa.Float(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code'),
    schema='grp'
    )
    op.create_table('group_accrual',
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('paying_company_id', sa.BigInteger(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('accrual_basis', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('accrued_to_date', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paying_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref'),
    schema='grp'
    )
    op.create_table('sku_bridge',
    sa.Column('master_sku', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('barcode', sa.String(length=60), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_sku'),
    schema='grp'
    )
    op.create_table('cash_pool_member',
    sa.Column('pool_id', sa.BigInteger(), nullable=False),
    sa.Column('bank_account_id', sa.BigInteger(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('min_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['grp.bank_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pool_id'], ['grp.cash_pool.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_id', 'bank_account_id', name='uq_cash_pool_member'),
    schema='grp'
    )
    op.create_table('transfer_pricing_agreement',
    sa.Column('from_company_id', sa.BigInteger(), nullable=False),
    sa.Column('to_company_id', sa.BigInteger(), nullable=False),
    sa.Column('product_category_id', sa.BigInteger(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('markup_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fixed_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_category_id'], ['wms.product_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_company_id', 'to_company_id', 'product_category_id', 'valid_from', name='uq_transfer_pricing_window'),
    schema='grp'
    )
    op.create_table('volume_rebate_accrual',
    sa.Column('vendor_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('period_kind', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_group_spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('matched_tier_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('accrued_rebate', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_profile_id'], ['grp.cross_company_vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_profile_id', 'period_kind', 'period_start', name='uq_rebate_accrual'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_volume_rebate_accrual_vendor_profile_id'), 'volume_rebate_accrual', ['vendor_profile_id'], unique=False, schema='grp')
    op.create_table('volume_rebate_tier',
    sa.Column('vendor_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('period_kind', sa.String(length=20), nullable=False),
    sa.Column('min_spend', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('max_spend', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('rebate_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_profile_id'], ['grp.cross_company_vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_profile_id', 'period_kind', 'min_spend', name='uq_rebate_tier'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_volume_rebate_tier_vendor_profile_id'), 'volume_rebate_tier', ['vendor_profile_id'], unique=False, schema='grp')
    op.create_table('cross_company_customer_link',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('local_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['local_customer_id'], ['sales.customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['grp.cross_company_customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'local_customer_id', name='uq_xc_customer_local'),
    sa.UniqueConstraint('profile_id', 'company_id', name='uq_xc_customer_link'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_cross_company_customer_link_profile_id'), 'cross_company_customer_link', ['profile_id'], unique=False, schema='grp')
    op.create_table('cross_company_vendor_link',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('local_vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['local_vendor_id'], ['purchase.vendor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['grp.cross_company_vendor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'local_vendor_id', name='uq_xc_vendor_local'),
    sa.UniqueConstraint('profile_id', 'company_id', name='uq_xc_vendor_link'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_cross_company_vendor_link_profile_id'), 'cross_company_vendor_link', ['profile_id'], unique=False, schema='grp')
    op.create_table('sku_bridge_member',
    sa.Column('bridge_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('local_product_id', sa.BigInteger(), nullable=False),
    sa.Column('local_sku', sa.String(length=60), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bridge_id'], ['grp.sku_bridge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['local_product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bridge_id', 'company_id', name='uq_sku_bridge_company'),
    sa.UniqueConstraint('company_id', 'local_product_id', name='uq_sku_bridge_local'),
    schema='grp'
    )
    op.create_index(op.f('ix_grp_sku_bridge_member_bridge_id'), 'sku_bridge_member', ['bridge_id'], unique=False, schema='grp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grp_sku_bridge_member_bridge_id'), table_name='sku_bridge_member', schema='grp')
    op.drop_table('sku_bridge_member', schema='grp')
    op.drop_index(op.f('ix_grp_cross_company_vendor_link_profile_id'), table_name='cross_company_vendor_link', schema='grp')
    op.drop_table('cross_company_vendor_link', schema='grp')
    op.drop_index(op.f('ix_grp_cross_company_customer_link_profile_id'), table_name='cross_company_customer_link', schema='grp')
    op.drop_table('cross_company_customer_link', schema='grp')
    op.drop_index(op.f('ix_grp_volume_rebate_tier_vendor_profile_id'), table_name='volume_rebate_tier', schema='grp')
    op.drop_table('volume_rebate_tier', schema='grp')
    op.drop_index(op.f('ix_grp_volume_rebate_accrual_vendor_profile_id'), table_name='volume_rebate_accrual', schema='grp')
    op.drop_table('volume_rebate_accrual', schema='grp')
    op.drop_table('transfer_pricing_agreement', schema='grp')
    op.drop_table('cash_pool_member', schema='grp')
    op.drop_table('sku_bridge', schema='grp')
    op.drop_table('group_accrual', schema='grp')
    op.drop_table('cross_company_vendor', schema='grp')
    op.drop_table('cross_company_customer', schema='grp')
    op.drop_table('cash_pool', schema='grp')
    op.drop_index(op.f('ix_grp_cash_forecast_snapshot_forecast_date'), table_name='cash_forecast_snapshot', schema='grp')
    op.drop_index(op.f('ix_grp_cash_forecast_snapshot_company_id'), table_name='cash_forecast_snapshot', schema='grp')
    op.drop_table('cash_forecast_snapshot', schema='grp')
    op.drop_index(op.f('ix_grp_brand_license_brand_code'), table_name='brand_license', schema='grp')
    op.drop_table('brand_license', schema='grp')
    op.drop_index(op.f('ix_grp_bank_account_company_id'), table_name='bank_account', schema='grp')
    op.drop_table('bank_account', schema='grp')
    op.drop_index(op.f('ix_grp_approval_substitution_primary_user_id'), table_name='approval_substitution', schema='grp')
    op.drop_table('approval_substitution', schema='grp')
    # ### end Alembic commands ###
