"""initial

Revision ID: ccb9aa50ec32
Revises: 
Create Date: 2026-04-30 05:34:41.586957
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ccb9aa50ec32'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_user_email'), 'user', ['email'], unique=True, schema='core')
    op.create_table('activity_log',
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_activity_log_action'), 'activity_log', ['action'], unique=False, schema='core')
    op.create_index(op.f('ix_core_activity_log_actor_id'), 'activity_log', ['actor_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_activity_log_block_hash'), 'activity_log', ['block_hash'], unique=False, schema='core')
    op.create_index(op.f('ix_core_activity_log_ref'), 'activity_log', ['ref'], unique=False, schema='core')
    op.create_table('audit_log',
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_model'), 'audit_log', ['model'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_record_id'), 'audit_log', ['record_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_request_id'), 'audit_log', ['request_id'], unique=False, schema='core')
    op.create_table('group',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('permission',
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', 'action', name='uq_permission_model_action'),
    schema='core'
    )
    op.create_index(op.f('ix_core_permission_model'), 'permission', ['model'], unique=False, schema='core')
    op.create_table('courier',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('tracking_url_template', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='wms'
    )
    op.create_table('product_category',
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('complete_name', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['wms.product_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='wms'
    )
    op.create_table('uom_category',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='wms'
    )
    op.create_table('warehouse',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='wms'
    )
    op.create_table('group_permission',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['core.group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['core.permission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_id'),
    schema='core'
    )
    op.create_table('user_group',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['core.group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    schema='core'
    )
    op.create_table('count_session',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('session_type', sa.String(length=10), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('responsible_id', sa.BigInteger(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('variance_threshold_pct', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsible_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['wms.warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_count_session_name'), 'count_session', ['name'], unique=True, schema='inventory')
    op.create_index(op.f('ix_inventory_count_session_state'), 'count_session', ['state'], unique=False, schema='inventory')
    op.create_table('dispatch_batch',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('courier_id', sa.BigInteger(), nullable=False),
    sa.Column('work_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receiver_name', sa.String(length=120), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_by', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['wms.courier.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispatched_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='outbound'
    )
    op.create_index(op.f('ix_outbound_dispatch_batch_name'), 'dispatch_batch', ['name'], unique=True, schema='outbound')
    op.create_index(op.f('ix_outbound_dispatch_batch_state'), 'dispatch_batch', ['state'], unique=False, schema='outbound')
    op.create_table('order',
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('courier_id', sa.BigInteger(), nullable=True),
    sa.Column('awb', sa.String(length=80), nullable=True),
    sa.Column('box_barcode', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('sla_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pick_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pack_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picker_id', sa.BigInteger(), nullable=True),
    sa.Column('packer_id', sa.BigInteger(), nullable=True),
    sa.Column('shipper_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['wms.courier.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['packer_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picker_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipper_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='outbound'
    )
    op.create_index(op.f('ix_outbound_order_awb'), 'order', ['awb'], unique=False, schema='outbound')
    op.create_index(op.f('ix_outbound_order_ref'), 'order', ['ref'], unique=True, schema='outbound')
    op.create_index(op.f('ix_outbound_order_state'), 'order', ['state'], unique=False, schema='outbound')
    op.create_table('uom',
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('uom_type', sa.String(length=10), nullable=False),
    sa.Column('factor', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('rounding', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['wms.uom_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_uom_cat_name'),
    schema='wms'
    )
    op.create_table('zone',
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['wms.warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_zone_warehouse_code'),
    schema='wms'
    )
    op.create_table('scan_item',
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('barcode', sa.String(length=80), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scanned_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['outbound.dispatch_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['outbound.order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scanned_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='outbound'
    )
    op.create_index(op.f('ix_outbound_scan_item_barcode'), 'scan_item', ['barcode'], unique=False, schema='outbound')
    op.create_index(op.f('ix_outbound_scan_item_batch_id'), 'scan_item', ['batch_id'], unique=False, schema='outbound')
    op.create_table('location',
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('complete_name', sa.String(length=500), nullable=True),
    sa.Column('usage', sa.String(length=20), nullable=False),
    sa.Column('barcode', sa.String(length=60), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['wms.warehouse.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['wms.zone.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'barcode', name='uq_location_barcode'),
    schema='wms'
    )
    op.create_table('product',
    sa.Column('default_code', sa.String(length=60), nullable=False),
    sa.Column('barcode', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('uom_id', sa.BigInteger(), nullable=False),
    sa.Column('list_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('standard_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['wms.product_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uom_id'], ['wms.uom.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('default_code', name='uq_product_default_code'),
    schema='wms'
    )
    op.create_index(op.f('ix_wms_product_default_code'), 'product', ['default_code'], unique=False, schema='wms')
    op.create_table('count_snapshot',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_before', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('qty_after', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory.count_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_count_snapshot_session_id'), 'count_snapshot', ['session_id'], unique=False, schema='inventory')
    op.create_table('count_task',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_user_id', sa.BigInteger(), nullable=True),
    sa.Column('expected_qty', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory.count_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_count_task_session_id'), 'count_task', ['session_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_count_task_state'), 'count_task', ['state'], unique=False, schema='inventory')
    op.create_table('transfer_type',
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('sequence_prefix', sa.String(length=8), nullable=False),
    sa.Column('default_source_location_id', sa.BigInteger(), nullable=True),
    sa.Column('default_dest_location_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_dest_location_id'], ['wms.location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_source_location_id'], ['wms.location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['wms.warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_transfer_type_code'),
    schema='inventory'
    )
    op.create_table('lot',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='uq_lot_product_name'),
    schema='wms'
    )
    op.create_table('pickface',
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('min_qty', sa.Float(), nullable=False),
    sa.Column('max_qty', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['wms.zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'code', name='uq_pickface_zone_code'),
    schema='wms'
    )
    op.create_table('rack',
    sa.Column('zone_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['wms.zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'code', name='uq_rack_zone_code'),
    schema='wms'
    )
    op.create_table('count_adjustment',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_variance', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=15), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['inventory.count_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['inventory.count_task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_count_adjustment_session_id'), 'count_adjustment', ['session_id'], unique=False, schema='inventory')
    op.create_table('count_entry',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['inventory.count_task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_count_entry_task_id'), 'count_entry', ['task_id'], unique=False, schema='inventory')
    op.create_table('stock_quant',
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'product_id', 'lot_id', name='uq_quant_location_product_lot'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_stock_quant_location_id'), 'stock_quant', ['location_id'], unique=False, schema='inventory')
    op.create_index(op.f('ix_inventory_stock_quant_product_id'), 'stock_quant', ['product_id'], unique=False, schema='inventory')
    op.create_table('transfer',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('transfer_type_id', sa.BigInteger(), nullable=False),
    sa.Column('source_location_id', sa.BigInteger(), nullable=False),
    sa.Column('dest_location_id', sa.BigInteger(), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dest_location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_type_id'], ['inventory.transfer_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_transfer_name'), 'transfer', ['name'], unique=True, schema='inventory')
    op.create_index(op.f('ix_inventory_transfer_state'), 'transfer', ['state'], unique=False, schema='inventory')
    op.create_table('order_line',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('qty_expected', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('qty_picked', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('qty_packed', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['outbound.order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='outbound'
    )
    op.create_index(op.f('ix_outbound_order_line_order_id'), 'order_line', ['order_id'], unique=False, schema='outbound')
    op.create_table('transfer_line',
    sa.Column('transfer_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('uom_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('source_location_id', sa.BigInteger(), nullable=True),
    sa.Column('dest_location_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity_demand', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('quantity_done', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dest_location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['inventory.transfer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['wms.uom.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_transfer_line_transfer_id'), 'transfer_line', ['transfer_id'], unique=False, schema='inventory')
    op.create_table('check',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_line_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('expected_qty', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('checked_by_id', sa.BigInteger(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['checked_by_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['outbound.order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_line_id'], ['outbound.order_line.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_index(op.f('ix_quality_check_order_id'), 'check', ['order_id'], unique=False, schema='quality')
    op.create_index(op.f('ix_quality_check_state'), 'check', ['state'], unique=False, schema='quality')
    op.create_table('defect',
    sa.Column('check_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('defect_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('root_cause', sa.String(length=2000), nullable=True),
    sa.Column('action_taken', sa.String(length=2000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['quality.check.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='quality'
    )
    op.create_index(op.f('ix_quality_defect_check_id'), 'defect', ['check_id'], unique=False, schema='quality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_defect_check_id'), table_name='defect', schema='quality')
    op.drop_table('defect', schema='quality')
    op.drop_index(op.f('ix_quality_check_state'), table_name='check', schema='quality')
    op.drop_index(op.f('ix_quality_check_order_id'), table_name='check', schema='quality')
    op.drop_table('check', schema='quality')
    op.drop_index(op.f('ix_inventory_transfer_line_transfer_id'), table_name='transfer_line', schema='inventory')
    op.drop_table('transfer_line', schema='inventory')
    op.drop_index(op.f('ix_outbound_order_line_order_id'), table_name='order_line', schema='outbound')
    op.drop_table('order_line', schema='outbound')
    op.drop_index(op.f('ix_inventory_transfer_state'), table_name='transfer', schema='inventory')
    op.drop_index(op.f('ix_inventory_transfer_name'), table_name='transfer', schema='inventory')
    op.drop_table('transfer', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_quant_product_id'), table_name='stock_quant', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_quant_location_id'), table_name='stock_quant', schema='inventory')
    op.drop_table('stock_quant', schema='inventory')
    op.drop_index(op.f('ix_inventory_count_entry_task_id'), table_name='count_entry', schema='inventory')
    op.drop_table('count_entry', schema='inventory')
    op.drop_index(op.f('ix_inventory_count_adjustment_session_id'), table_name='count_adjustment', schema='inventory')
    op.drop_table('count_adjustment', schema='inventory')
    op.drop_table('rack', schema='wms')
    op.drop_table('pickface', schema='wms')
    op.drop_table('lot', schema='wms')
    op.drop_table('transfer_type', schema='inventory')
    op.drop_index(op.f('ix_inventory_count_task_state'), table_name='count_task', schema='inventory')
    op.drop_index(op.f('ix_inventory_count_task_session_id'), table_name='count_task', schema='inventory')
    op.drop_table('count_task', schema='inventory')
    op.drop_index(op.f('ix_inventory_count_snapshot_session_id'), table_name='count_snapshot', schema='inventory')
    op.drop_table('count_snapshot', schema='inventory')
    op.drop_index(op.f('ix_wms_product_default_code'), table_name='product', schema='wms')
    op.drop_table('product', schema='wms')
    op.drop_table('location', schema='wms')
    op.drop_index(op.f('ix_outbound_scan_item_batch_id'), table_name='scan_item', schema='outbound')
    op.drop_index(op.f('ix_outbound_scan_item_barcode'), table_name='scan_item', schema='outbound')
    op.drop_table('scan_item', schema='outbound')
    op.drop_table('zone', schema='wms')
    op.drop_table('uom', schema='wms')
    op.drop_index(op.f('ix_outbound_order_state'), table_name='order', schema='outbound')
    op.drop_index(op.f('ix_outbound_order_ref'), table_name='order', schema='outbound')
    op.drop_index(op.f('ix_outbound_order_awb'), table_name='order', schema='outbound')
    op.drop_table('order', schema='outbound')
    op.drop_index(op.f('ix_outbound_dispatch_batch_state'), table_name='dispatch_batch', schema='outbound')
    op.drop_index(op.f('ix_outbound_dispatch_batch_name'), table_name='dispatch_batch', schema='outbound')
    op.drop_table('dispatch_batch', schema='outbound')
    op.drop_index(op.f('ix_inventory_count_session_state'), table_name='count_session', schema='inventory')
    op.drop_index(op.f('ix_inventory_count_session_name'), table_name='count_session', schema='inventory')
    op.drop_table('count_session', schema='inventory')
    op.drop_table('user_group', schema='core')
    op.drop_table('group_permission', schema='core')
    op.drop_table('warehouse', schema='wms')
    op.drop_table('uom_category', schema='wms')
    op.drop_table('product_category', schema='wms')
    op.drop_table('courier', schema='wms')
    op.drop_index(op.f('ix_core_permission_model'), table_name='permission', schema='core')
    op.drop_table('permission', schema='core')
    op.drop_table('group', schema='core')
    op.drop_index(op.f('ix_core_audit_log_request_id'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_record_id'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_model'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_actor_id'), table_name='audit_log', schema='core')
    op.drop_table('audit_log', schema='core')
    op.drop_index(op.f('ix_core_activity_log_ref'), table_name='activity_log', schema='core')
    op.drop_index(op.f('ix_core_activity_log_block_hash'), table_name='activity_log', schema='core')
    op.drop_index(op.f('ix_core_activity_log_actor_id'), table_name='activity_log', schema='core')
    op.drop_index(op.f('ix_core_activity_log_action'), table_name='activity_log', schema='core')
    op.drop_table('activity_log', schema='core')
    op.drop_index(op.f('ix_core_user_email'), table_name='user', schema='core')
    op.drop_table('user', schema='core')
    # ### end Alembic commands ###
