"""phase 10: sales advanced + multi-company FKs on key tables

Revision ID: eab65c7a4ca8
Revises: fec43c414dc0
Create Date: 2026-05-01 02:23:17.415762
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'eab65c7a4ca8'
down_revision: str | Sequence[str] | None = 'fec43c414dc0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_margin',
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('platform_fees', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('return_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net_margin', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('margin_pct', sa.Float(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'channel', 'period_start', name='uq_channel_margin_window'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_channel_margin_channel'), 'channel_margin', ['channel'], unique=False, schema='sales')
    op.create_table('lost_reason',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='sales'
    )
    op.create_table('pricelist',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('base', sa.String(length=30), nullable=False),
    sa.Column('customer_group', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='sales'
    )
    op.create_table('sales_team',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('manager_id', sa.BigInteger(), nullable=True),
    sa.Column('default_commission_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='sales'
    )
    op.create_table('customer_ltv_snapshot',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('revenue_90d', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_count_90d', sa.Integer(), nullable=False),
    sa.Column('repeat_rate', sa.Float(), nullable=False),
    sa.Column('return_rate', sa.Float(), nullable=False),
    sa.Column('avg_order_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['sales.customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_customer_ltv_snapshot_customer_id'), 'customer_ltv_snapshot', ['customer_id'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_customer_ltv_snapshot_snapshot_date'), 'customer_ltv_snapshot', ['snapshot_date'], unique=False, schema='sales')
    op.create_table('pricelist_rule',
    sa.Column('pricelist_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_category_id', sa.BigInteger(), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pricelist_id'], ['sales.pricelist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id'], ['wms.product_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_pricelist_rule_pricelist_id'), 'pricelist_rule', ['pricelist_id'], unique=False, schema='sales')
    op.create_table('intercompany_transfer',
    sa.Column('sales_order_id', sa.BigInteger(), nullable=False),
    sa.Column('so_company_id', sa.BigInteger(), nullable=False),
    sa.Column('fulfillment_company_id', sa.BigInteger(), nullable=False),
    sa.Column('mirror_po_id', sa.BigInteger(), nullable=True),
    sa.Column('transfer_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('transfer_pricing_method', sa.String(length=20), nullable=False),
    sa.Column('transfer_pricing_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fulfillment_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mirror_po_id'], ['purchase.purchase_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales.sales_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['so_company_id'], ['core.company.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_intercompany_transfer_sales_order_id'), 'intercompany_transfer', ['sales_order_id'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_intercompany_transfer_state'), 'intercompany_transfer', ['state'], unique=False, schema='sales')
    op.create_table('multi_platform_order',
    sa.Column('sales_order_id', sa.BigInteger(), nullable=False),
    sa.Column('platform_order_id', sa.BigInteger(), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('commission_deducted', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_subsidy', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_order_id'], ['ops.platform_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales.sales_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sales_order_id', 'platform_order_id', name='uq_multi_platform_pair'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_multi_platform_order_platform_order_id'), 'multi_platform_order', ['platform_order_id'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_multi_platform_order_sales_order_id'), 'multi_platform_order', ['sales_order_id'], unique=False, schema='sales')
    op.create_table('return_order',
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('sales_order_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_location_id', sa.BigInteger(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['core.company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receipt_location_id'], ['wms.location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales.sales_order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_return_order_ref'), 'return_order', ['ref'], unique=True, schema='sales')
    op.create_index(op.f('ix_sales_return_order_sales_order_id'), 'return_order', ['sales_order_id'], unique=False, schema='sales')
    op.create_index(op.f('ix_sales_return_order_state'), 'return_order', ['state'], unique=False, schema='sales')
    op.create_table('return_line',
    sa.Column('return_order_id', sa.BigInteger(), nullable=False),
    sa.Column('so_line_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_returned', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('qty_restocked', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('qty_scrapped', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reason_code', sa.String(length=30), nullable=False),
    sa.Column('reason_note', sa.String(length=500), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_order_id'], ['sales.return_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['so_line_id'], ['sales.so_line.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='sales'
    )
    op.create_index(op.f('ix_sales_return_line_return_order_id'), 'return_line', ['return_order_id'], unique=False, schema='sales')
    op.add_column('journal_entry', sa.Column('company_id', sa.BigInteger(), nullable=True), schema='accounting')
    op.create_index(op.f('ix_accounting_journal_entry_company_id'), 'journal_entry', ['company_id'], unique=False, schema='accounting')
    op.create_foreign_key(None, 'journal_entry', 'company', ['company_id'], ['id'], source_schema='accounting', referent_schema='core', ondelete='SET NULL')
    op.add_column('order', sa.Column('company_id', sa.BigInteger(), nullable=True), schema='outbound')
    op.create_index(op.f('ix_outbound_order_company_id'), 'order', ['company_id'], unique=False, schema='outbound')
    op.create_foreign_key(None, 'order', 'company', ['company_id'], ['id'], source_schema='outbound', referent_schema='core', ondelete='SET NULL')
    op.add_column('purchase_order', sa.Column('company_id', sa.BigInteger(), nullable=True), schema='purchase')
    op.create_index(op.f('ix_purchase_purchase_order_company_id'), 'purchase_order', ['company_id'], unique=False, schema='purchase')
    op.create_foreign_key(None, 'purchase_order', 'company', ['company_id'], ['id'], source_schema='purchase', referent_schema='core', ondelete='SET NULL')
    op.add_column('customer', sa.Column('company_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('customer', sa.Column('pricelist_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('customer', sa.Column('sales_team_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('customer', sa.Column('payment_term_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('customer', sa.Column('customer_group', sa.String(length=20), nullable=False), schema='sales')
    op.add_column('customer', sa.Column('credit_consumed', sa.Numeric(precision=14, scale=2), nullable=False), schema='sales')
    op.add_column('customer', sa.Column('ltv_score', sa.Float(), nullable=False), schema='sales')
    op.add_column('customer', sa.Column('blocked', sa.Boolean(), nullable=False), schema='sales')
    op.add_column('customer', sa.Column('blocked_reason', sa.String(length=500), nullable=True), schema='sales')
    op.create_index(op.f('ix_sales_customer_company_id'), 'customer', ['company_id'], unique=False, schema='sales')
    op.create_foreign_key(None, 'customer', 'pricelist', ['pricelist_id'], ['id'], source_schema='sales', referent_schema='sales', ondelete='SET NULL')
    op.create_foreign_key('fk_customer_payment_term', 'customer', 'payment_term', ['payment_term_id'], ['id'], source_schema='sales', referent_schema='purchase', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'customer', 'sales_team', ['sales_team_id'], ['id'], source_schema='sales', referent_schema='sales', ondelete='SET NULL')
    op.create_foreign_key(None, 'customer', 'company', ['company_id'], ['id'], source_schema='sales', referent_schema='core', ondelete='SET NULL')
    op.add_column('sales_order', sa.Column('company_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('sales_team_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('salesperson_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=False), schema='sales')
    op.add_column('sales_order', sa.Column('payment_term_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('pricelist_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('lost_reason_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('won_at', sa.DateTime(timezone=True), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('lost_at', sa.DateTime(timezone=True), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('revision', sa.Integer(), nullable=False), schema='sales')
    op.add_column('sales_order', sa.Column('revision_of_id', sa.BigInteger(), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('promise_date', sa.Date(), nullable=True), schema='sales')
    op.add_column('sales_order', sa.Column('p2d_confidence', sa.Float(), nullable=False), schema='sales')
    op.create_index(op.f('ix_sales_sales_order_company_id'), 'sales_order', ['company_id'], unique=False, schema='sales')
    op.create_foreign_key('fk_so_payment_term', 'sales_order', 'payment_term', ['payment_term_id'], ['id'], source_schema='sales', referent_schema='purchase', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'sales_order', 'user', ['salesperson_id'], ['id'], source_schema='sales', referent_schema='core', ondelete='SET NULL')
    op.create_foreign_key(None, 'sales_order', 'pricelist', ['pricelist_id'], ['id'], source_schema='sales', referent_schema='sales', ondelete='SET NULL')
    op.create_foreign_key(None, 'sales_order', 'company', ['company_id'], ['id'], source_schema='sales', referent_schema='core', ondelete='SET NULL')
    op.create_foreign_key(None, 'sales_order', 'sales_team', ['sales_team_id'], ['id'], source_schema='sales', referent_schema='sales', ondelete='SET NULL')
    op.create_foreign_key('fk_so_revision_of', 'sales_order', 'sales_order', ['revision_of_id'], ['id'], source_schema='sales', referent_schema='sales', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'sales_order', 'lost_reason', ['lost_reason_id'], ['id'], source_schema='sales', referent_schema='sales', ondelete='SET NULL')
    op.add_column('warehouse', sa.Column('company_id', sa.BigInteger(), nullable=True), schema='wms')
    op.create_index(op.f('ix_wms_warehouse_company_id'), 'warehouse', ['company_id'], unique=False, schema='wms')
    op.create_foreign_key(None, 'warehouse', 'company', ['company_id'], ['id'], source_schema='wms', referent_schema='core', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse', schema='wms', type_='foreignkey')
    op.drop_index(op.f('ix_wms_warehouse_company_id'), table_name='warehouse', schema='wms')
    op.drop_column('warehouse', 'company_id', schema='wms')
    op.drop_constraint(None, 'sales_order', schema='sales', type_='foreignkey')
    op.drop_constraint('fk_so_revision_of', 'sales_order', schema='sales', type_='foreignkey')
    op.drop_constraint(None, 'sales_order', schema='sales', type_='foreignkey')
    op.drop_constraint(None, 'sales_order', schema='sales', type_='foreignkey')
    op.drop_constraint(None, 'sales_order', schema='sales', type_='foreignkey')
    op.drop_constraint(None, 'sales_order', schema='sales', type_='foreignkey')
    op.drop_constraint('fk_so_payment_term', 'sales_order', schema='sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_sales_order_company_id'), table_name='sales_order', schema='sales')
    op.drop_column('sales_order', 'p2d_confidence', schema='sales')
    op.drop_column('sales_order', 'promise_date', schema='sales')
    op.drop_column('sales_order', 'revision_of_id', schema='sales')
    op.drop_column('sales_order', 'revision', schema='sales')
    op.drop_column('sales_order', 'lost_at', schema='sales')
    op.drop_column('sales_order', 'won_at', schema='sales')
    op.drop_column('sales_order', 'lost_reason_id', schema='sales')
    op.drop_column('sales_order', 'pricelist_id', schema='sales')
    op.drop_column('sales_order', 'payment_term_id', schema='sales')
    op.drop_column('sales_order', 'commission_pct', schema='sales')
    op.drop_column('sales_order', 'salesperson_id', schema='sales')
    op.drop_column('sales_order', 'sales_team_id', schema='sales')
    op.drop_column('sales_order', 'company_id', schema='sales')
    op.drop_constraint(None, 'customer', schema='sales', type_='foreignkey')
    op.drop_constraint(None, 'customer', schema='sales', type_='foreignkey')
    op.drop_constraint('fk_customer_payment_term', 'customer', schema='sales', type_='foreignkey')
    op.drop_constraint(None, 'customer', schema='sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_customer_company_id'), table_name='customer', schema='sales')
    op.drop_column('customer', 'blocked_reason', schema='sales')
    op.drop_column('customer', 'blocked', schema='sales')
    op.drop_column('customer', 'ltv_score', schema='sales')
    op.drop_column('customer', 'credit_consumed', schema='sales')
    op.drop_column('customer', 'customer_group', schema='sales')
    op.drop_column('customer', 'payment_term_id', schema='sales')
    op.drop_column('customer', 'sales_team_id', schema='sales')
    op.drop_column('customer', 'pricelist_id', schema='sales')
    op.drop_column('customer', 'company_id', schema='sales')
    op.drop_constraint(None, 'purchase_order', schema='purchase', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_purchase_order_company_id'), table_name='purchase_order', schema='purchase')
    op.drop_column('purchase_order', 'company_id', schema='purchase')
    op.drop_constraint(None, 'order', schema='outbound', type_='foreignkey')
    op.drop_index(op.f('ix_outbound_order_company_id'), table_name='order', schema='outbound')
    op.drop_column('order', 'company_id', schema='outbound')
    op.drop_constraint(None, 'journal_entry', schema='accounting', type_='foreignkey')
    op.drop_index(op.f('ix_accounting_journal_entry_company_id'), table_name='journal_entry', schema='accounting')
    op.drop_column('journal_entry', 'company_id', schema='accounting')
    op.drop_index(op.f('ix_sales_return_line_return_order_id'), table_name='return_line', schema='sales')
    op.drop_table('return_line', schema='sales')
    op.drop_index(op.f('ix_sales_return_order_state'), table_name='return_order', schema='sales')
    op.drop_index(op.f('ix_sales_return_order_sales_order_id'), table_name='return_order', schema='sales')
    op.drop_index(op.f('ix_sales_return_order_ref'), table_name='return_order', schema='sales')
    op.drop_table('return_order', schema='sales')
    op.drop_index(op.f('ix_sales_multi_platform_order_sales_order_id'), table_name='multi_platform_order', schema='sales')
    op.drop_index(op.f('ix_sales_multi_platform_order_platform_order_id'), table_name='multi_platform_order', schema='sales')
    op.drop_table('multi_platform_order', schema='sales')
    op.drop_index(op.f('ix_sales_intercompany_transfer_state'), table_name='intercompany_transfer', schema='sales')
    op.drop_index(op.f('ix_sales_intercompany_transfer_sales_order_id'), table_name='intercompany_transfer', schema='sales')
    op.drop_table('intercompany_transfer', schema='sales')
    op.drop_index(op.f('ix_sales_pricelist_rule_pricelist_id'), table_name='pricelist_rule', schema='sales')
    op.drop_table('pricelist_rule', schema='sales')
    op.drop_index(op.f('ix_sales_customer_ltv_snapshot_snapshot_date'), table_name='customer_ltv_snapshot', schema='sales')
    op.drop_index(op.f('ix_sales_customer_ltv_snapshot_customer_id'), table_name='customer_ltv_snapshot', schema='sales')
    op.drop_table('customer_ltv_snapshot', schema='sales')
    op.drop_table('sales_team', schema='sales')
    op.drop_table('pricelist', schema='sales')
    op.drop_table('lost_reason', schema='sales')
    op.drop_index(op.f('ix_sales_channel_margin_channel'), table_name='channel_margin', schema='sales')
    op.drop_table('channel_margin', schema='sales')
    # ### end Alembic commands ###
