"""merge advanced: wms+purchase+mfg odoo 19 parity tables

Revision ID: fec43c414dc0
Revises: 5ecd11f789ab
Create Date: 2026-05-01 02:18:18.394432
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fec43c414dc0'
down_revision: str | Sequence[str] | None = '5ecd11f789ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_type',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('max_weight_kg', sa.Float(), nullable=True),
    sa.Column('barcode', sa.String(length=60), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('name'),
    schema='inventory'
    )
    op.create_table('routing',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='mfg'
    )
    op.create_table('payment_term',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='purchase'
    )
    op.create_table('procurement_budget',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('project_code', sa.String(length=40), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('committed_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('auto_block_overrun', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='purchase'
    )
    op.create_index(op.f('ix_purchase_procurement_budget_project_code'), 'procurement_budget', ['project_code'], unique=False, schema='purchase')
    op.create_table('production_shift',
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['wms.warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_shift_warehouse_code'),
    schema='mfg'
    )
    op.create_table('work_center',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('time_efficiency', sa.Float(), nullable=False),
    sa.Column('cost_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('oee_target', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['wms.warehouse.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='mfg'
    )
    op.create_table('payment_term_line',
    sa.Column('payment_term_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('value_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_term_id'], ['purchase.payment_term.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='purchase'
    )
    op.create_table('landed_cost',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('split_method', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['purchase.vendor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='inventory'
    )
    op.create_table('routing_operation',
    sa.Column('routing_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('work_center_id', sa.BigInteger(), nullable=False),
    sa.Column('default_duration', sa.Integer(), nullable=False),
    sa.Column('setup_duration', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routing_id'], ['mfg.routing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_center_id'], ['mfg.work_center.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='mfg'
    )
    op.create_index(op.f('ix_mfg_routing_operation_routing_id'), 'routing_operation', ['routing_id'], unique=False, schema='mfg')
    op.create_table('work_center_oee',
    sa.Column('work_center_id', sa.BigInteger(), nullable=False),
    sa.Column('shift_id', sa.BigInteger(), nullable=True),
    sa.Column('oee_date', sa.Date(), nullable=False),
    sa.Column('planned_time', sa.Integer(), nullable=False),
    sa.Column('available_time', sa.Integer(), nullable=False),
    sa.Column('run_time', sa.Integer(), nullable=False),
    sa.Column('ideal_cycle_time', sa.Float(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('good_units', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('oee', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['mfg.production_shift.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_center_id'], ['mfg.work_center.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_center_id', 'oee_date', 'shift_id', name='uq_oee_wc_date_shift'),
    schema='mfg'
    )
    op.create_index(op.f('ix_mfg_work_center_oee_work_center_id'), 'work_center_oee', ['work_center_id'], unique=False, schema='mfg')
    op.create_table('po_consolidation_proposal',
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('original_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('estimated_saving', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('saving_pct', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['purchase.vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='purchase'
    )
    op.create_index(op.f('ix_purchase_po_consolidation_proposal_vendor_id'), 'po_consolidation_proposal', ['vendor_id'], unique=False, schema='purchase')
    op.create_table('vendor_document',
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('alert_days_before', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['purchase.vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='purchase'
    )
    op.create_index(op.f('ix_purchase_vendor_document_expiry_date'), 'vendor_document', ['expiry_date'], unique=False, schema='purchase')
    op.create_index(op.f('ix_purchase_vendor_document_vendor_id'), 'vendor_document', ['vendor_id'], unique=False, schema='purchase')
    op.create_table('vendor_performance',
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('on_time_rate', sa.Float(), nullable=False),
    sa.Column('fill_rate', sa.Float(), nullable=False),
    sa.Column('quality_rate', sa.Float(), nullable=False),
    sa.Column('price_stability', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('po_count', sa.Integer(), nullable=False),
    sa.Column('receipt_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['purchase.vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'period_year', 'period_month', name='uq_vendor_perf_period'),
    schema='purchase'
    )
    op.create_index(op.f('ix_purchase_vendor_performance_vendor_id'), 'vendor_performance', ['vendor_id'], unique=False, schema='purchase')
    op.create_table('landed_cost_line',
    sa.Column('landed_cost_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('split_method', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounting.account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['landed_cost_id'], ['inventory.landed_cost.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('package',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('package_type_id', sa.BigInteger(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_type_id'], ['inventory.package_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory.package.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='inventory'
    )
    op.create_table('putaway_rule',
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('location_dest_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_category_id', sa.BigInteger(), nullable=True),
    sa.Column('package_type_id', sa.BigInteger(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('capacity_count', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_dest_id'], ['wms.location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_type_id'], ['inventory.package_type.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_category_id'], ['wms.product_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_putaway_rule_location_id'), 'putaway_rule', ['location_id'], unique=False, schema='inventory')
    op.create_table('reorder_rule',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_min', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('qty_max', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('qty_multiple', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_qty_ordered', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['wms.warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uq_reorder_product_location'),
    schema='inventory'
    )
    op.create_table('batch_consolidation',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_mos', sa.Integer(), nullable=False),
    sa.Column('total_qty', sa.Float(), nullable=False),
    sa.Column('setup_saving_minutes', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mfg'
    )
    op.create_index(op.f('ix_mfg_batch_consolidation_product_id'), 'batch_consolidation', ['product_id'], unique=False, schema='mfg')
    op.create_table('demand_signal',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('avg_daily_sales', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Float(), nullable=False),
    sa.Column('current_on_hand', sa.Float(), nullable=False),
    sa.Column('suggested_qty', sa.Float(), nullable=False),
    sa.Column('suggested_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('converted_po_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['converted_po_id'], ['purchase.purchase_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['purchase.vendor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='purchase'
    )
    op.create_index(op.f('ix_purchase_demand_signal_product_id'), 'demand_signal', ['product_id'], unique=False, schema='purchase')
    op.create_table('po_consolidation_item',
    sa.Column('proposal_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['purchase.po_consolidation_proposal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase.purchase_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='purchase'
    )
    op.create_table('purchase_bill',
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('journal_entry_id', sa.BigInteger(), nullable=False),
    sa.Column('bill_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['accounting.journal_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase.purchase_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'journal_entry_id', name='uq_po_bill'),
    schema='purchase'
    )
    op.create_index(op.f('ix_purchase_purchase_bill_purchase_order_id'), 'purchase_bill', ['purchase_order_id'], unique=False, schema='purchase')
    op.create_table('supplier_pricelist',
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['purchase.vendor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='purchase'
    )
    op.create_index(op.f('ix_purchase_supplier_pricelist_product_id'), 'supplier_pricelist', ['product_id'], unique=False, schema='purchase')
    op.create_index(op.f('ix_purchase_supplier_pricelist_vendor_id'), 'supplier_pricelist', ['vendor_id'], unique=False, schema='purchase')
    op.create_table('wht_certificate',
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('certificate_no', sa.String(length=40), nullable=True),
    sa.Column('wht_type', sa.String(length=10), nullable=False),
    sa.Column('wht_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('wht_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase.purchase_order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['purchase.vendor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_no'),
    schema='purchase'
    )
    op.create_index(op.f('ix_purchase_wht_certificate_purchase_order_id'), 'wht_certificate', ['purchase_order_id'], unique=False, schema='purchase')
    op.create_table('scrap_order',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('package_id', sa.BigInteger(), nullable=True),
    sa.Column('uom_id', sa.BigInteger(), nullable=False),
    sa.Column('scrap_qty', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('source_location_id', sa.BigInteger(), nullable=False),
    sa.Column('scrap_location_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=True),
    sa.Column('scrap_reason', sa.Text(), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['inventory.package.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scrap_location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_location_id'], ['wms.location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uom_id'], ['wms.uom.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='inventory'
    )
    op.create_table('bom_version',
    sa.Column('bom_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['mfg.bom_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mfg'
    )
    op.create_index(op.f('ix_mfg_bom_version_bom_id'), 'bom_version', ['bom_id'], unique=False, schema='mfg')
    op.create_table('landed_cost_transfer',
    sa.Column('landed_cost_id', sa.BigInteger(), nullable=False),
    sa.Column('transfer_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['landed_cost_id'], ['inventory.landed_cost.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['inventory.transfer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landed_cost_id', 'transfer_id', name='uq_lc_transfer'),
    schema='inventory'
    )
    op.create_table('batch_consolidation_item',
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('mo_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['mfg.batch_consolidation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mo_id'], ['mfg.manufacturing_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mfg'
    )
    op.create_table('mo_component_line',
    sa.Column('mo_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('uom_id', sa.BigInteger(), nullable=True),
    sa.Column('qty_demand', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('qty_done', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('source_location_id', sa.BigInteger(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mo_id'], ['mfg.manufacturing_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_location_id'], ['wms.location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uom_id'], ['wms.uom.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mfg'
    )
    op.create_index(op.f('ix_mfg_mo_component_line_mo_id'), 'mo_component_line', ['mo_id'], unique=False, schema='mfg')
    op.create_table('mo_production_signal',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('bom_id', sa.BigInteger(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('avg_daily_demand', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('wip_qty', sa.Float(), nullable=False),
    sa.Column('suggested_qty', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('converted_mo_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['mfg.bom_template.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_mo_id'], ['mfg.manufacturing_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mfg'
    )
    op.create_index(op.f('ix_mfg_mo_production_signal_product_id'), 'mo_production_signal', ['product_id'], unique=False, schema='mfg')
    op.create_table('mo_scrap',
    sa.Column('mo_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('scrap_reason', sa.String(length=240), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('scrapped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mo_id'], ['mfg.manufacturing_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='mfg'
    )
    op.create_index(op.f('ix_mfg_mo_scrap_mo_id'), 'mo_scrap', ['mo_id'], unique=False, schema='mfg')
    op.create_table('unbuild_order',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('bom_id', sa.BigInteger(), nullable=False),
    sa.Column('mo_id', sa.BigInteger(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['mfg.bom_template.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['wms.location.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['wms.lot.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mo_id'], ['mfg.manufacturing_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='mfg'
    )
    op.create_table('stock_valuation_layer',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('transfer_id', sa.BigInteger(), nullable=True),
    sa.Column('transfer_line_id', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('remaining_qty', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('remaining_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('landed_cost_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['landed_cost_id'], ['inventory.landed_cost.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['wms.product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['inventory.transfer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_line_id'], ['inventory.transfer_line.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['core.user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_stock_valuation_layer_product_id'), 'stock_valuation_layer', ['product_id'], unique=False, schema='inventory')
    op.add_column('transfer', sa.Column('is_return', sa.Boolean(), nullable=False), schema='inventory')
    op.add_column('transfer', sa.Column('origin_transfer_id', sa.BigInteger(), nullable=True), schema='inventory')
    op.add_column('transfer', sa.Column('backorder_id', sa.BigInteger(), nullable=True), schema='inventory')
    op.add_column('transfer', sa.Column('responsible_id', sa.BigInteger(), nullable=True), schema='inventory')
    op.add_column('transfer', sa.Column('carrier_id', sa.BigInteger(), nullable=True), schema='inventory')
    op.add_column('transfer', sa.Column('carrier_tracking_ref', sa.String(length=120), nullable=True), schema='inventory')
    op.alter_column('transfer', 'note',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True,
               schema='inventory')
    op.create_foreign_key(None, 'transfer', 'transfer', ['origin_transfer_id'], ['id'], source_schema='inventory', referent_schema='inventory', ondelete='SET NULL')
    op.create_foreign_key(None, 'transfer', 'courier', ['carrier_id'], ['id'], source_schema='inventory', referent_schema='wms', ondelete='SET NULL')
    op.create_foreign_key(None, 'transfer', 'user', ['responsible_id'], ['id'], source_schema='inventory', referent_schema='core', ondelete='SET NULL')
    op.create_foreign_key(None, 'transfer', 'transfer', ['backorder_id'], ['id'], source_schema='inventory', referent_schema='inventory', ondelete='SET NULL')
    op.add_column('transfer_line', sa.Column('quantity_reserved', sa.Numeric(precision=16, scale=4), nullable=False), schema='inventory')
    op.add_column('transfer_line', sa.Column('package_id', sa.BigInteger(), nullable=True), schema='inventory')
    op.add_column('transfer_line', sa.Column('result_package_id', sa.BigInteger(), nullable=True), schema='inventory')
    op.create_foreign_key(None, 'transfer_line', 'package', ['result_package_id'], ['id'], source_schema='inventory', referent_schema='inventory', ondelete='SET NULL')
    op.create_foreign_key(None, 'transfer_line', 'package', ['package_id'], ['id'], source_schema='inventory', referent_schema='inventory', ondelete='SET NULL')
    op.add_column('bom_line', sa.Column('line_type', sa.String(length=10), nullable=False), schema='mfg')
    op.add_column('bom_line', sa.Column('sequence', sa.Integer(), nullable=False), schema='mfg')
    op.add_column('bom_line', sa.Column('country_of_origin', sa.String(length=3), nullable=True), schema='mfg')
    op.add_column('bom_line', sa.Column('hs_code', sa.String(length=15), nullable=True), schema='mfg')
    op.add_column('bom_template', sa.Column('version', sa.Integer(), nullable=False), schema='mfg')
    op.add_column('bom_template', sa.Column('effective_from', sa.Date(), nullable=True), schema='mfg')
    op.add_column('bom_template', sa.Column('effective_to', sa.Date(), nullable=True), schema='mfg')
    op.add_column('bom_template', sa.Column('routing_id', sa.BigInteger(), nullable=True), schema='mfg')
    op.create_foreign_key(None, 'bom_template', 'routing', ['routing_id'], ['id'], source_schema='mfg', referent_schema='mfg', ondelete='SET NULL')
    op.add_column('manufacturing_order', sa.Column('qty_scrap', sa.Numeric(precision=14, scale=4), nullable=False), schema='mfg')
    op.add_column('manufacturing_order', sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True), schema='mfg')
    op.add_column('manufacturing_order', sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True), schema='mfg')
    op.add_column('manufacturing_order', sa.Column('lot_id', sa.BigInteger(), nullable=True), schema='mfg')
    op.add_column('manufacturing_order', sa.Column('material_cost', sa.Numeric(precision=16, scale=2), nullable=False), schema='mfg')
    op.add_column('manufacturing_order', sa.Column('labor_cost', sa.Numeric(precision=16, scale=2), nullable=False), schema='mfg')
    op.add_column('manufacturing_order', sa.Column('overhead_cost', sa.Numeric(precision=16, scale=2), nullable=False), schema='mfg')
    op.add_column('manufacturing_order', sa.Column('total_cost', sa.Numeric(precision=16, scale=2), nullable=False), schema='mfg')
    op.add_column('manufacturing_order', sa.Column('subcon_recon_id', sa.BigInteger(), nullable=True), schema='mfg')
    op.create_foreign_key(None, 'manufacturing_order', 'subcon_recon', ['subcon_recon_id'], ['id'], source_schema='mfg', referent_schema='mfg', ondelete='SET NULL')
    op.create_foreign_key(None, 'manufacturing_order', 'lot', ['lot_id'], ['id'], source_schema='mfg', referent_schema='wms', ondelete='SET NULL')
    op.add_column('subcon_vendor', sa.Column('variance_rate', sa.Float(), nullable=False), schema='mfg')
    op.add_column('subcon_vendor', sa.Column('quality_score', sa.Float(), nullable=False), schema='mfg')
    op.add_column('work_order', sa.Column('sequence', sa.Integer(), nullable=False), schema='mfg')
    op.add_column('work_order', sa.Column('work_center_id', sa.BigInteger(), nullable=True), schema='mfg')
    op.add_column('work_order', sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True), schema='mfg')
    op.add_column('work_order', sa.Column('setup_duration', sa.Integer(), nullable=False), schema='mfg')
    op.add_column('work_order', sa.Column('remaining_minutes', sa.Integer(), nullable=True), schema='mfg')
    op.add_column('work_order', sa.Column('qty_production', sa.Numeric(precision=14, scale=4), nullable=False), schema='mfg')
    op.add_column('work_order', sa.Column('shift_id', sa.BigInteger(), nullable=True), schema='mfg')
    op.create_foreign_key(None, 'work_order', 'production_shift', ['shift_id'], ['id'], source_schema='mfg', referent_schema='mfg', ondelete='SET NULL')
    op.create_foreign_key(None, 'work_order', 'work_center', ['work_center_id'], ['id'], source_schema='mfg', referent_schema='mfg', ondelete='SET NULL')
    op.add_column('po_line', sa.Column('tax_id', sa.BigInteger(), nullable=True), schema='purchase')
    op.add_column('po_line', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False), schema='purchase')
    op.add_column('po_line', sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False), schema='purchase')
    op.add_column('po_line', sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False), schema='purchase')
    op.create_foreign_key(None, 'po_line', 'tax_rate', ['tax_id'], ['id'], source_schema='purchase', referent_schema='accounting', ondelete='SET NULL')
    op.add_column('purchase_order', sa.Column('note_internal', sa.Text(), nullable=True), schema='purchase')
    op.add_column('purchase_order', sa.Column('note_vendor', sa.Text(), nullable=True), schema='purchase')
    op.add_column('purchase_order', sa.Column('incoterms', sa.String(length=10), nullable=True), schema='purchase')
    op.add_column('purchase_order', sa.Column('buyer_id', sa.BigInteger(), nullable=True), schema='purchase')
    op.add_column('purchase_order', sa.Column('payment_term_id', sa.BigInteger(), nullable=True), schema='purchase')
    op.add_column('purchase_order', sa.Column('approval_state', sa.String(length=20), nullable=False), schema='purchase')
    op.add_column('purchase_order', sa.Column('approver_id', sa.BigInteger(), nullable=True), schema='purchase')
    op.add_column('purchase_order', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True), schema='purchase')
    op.add_column('purchase_order', sa.Column('budget_id', sa.BigInteger(), nullable=True), schema='purchase')
    op.create_foreign_key(None, 'purchase_order', 'procurement_budget', ['budget_id'], ['id'], source_schema='purchase', referent_schema='purchase', ondelete='SET NULL')
    op.create_foreign_key(None, 'purchase_order', 'user', ['approver_id'], ['id'], source_schema='purchase', referent_schema='core', ondelete='SET NULL')
    op.create_foreign_key(None, 'purchase_order', 'user', ['buyer_id'], ['id'], source_schema='purchase', referent_schema='core', ondelete='SET NULL')
    op.create_foreign_key(None, 'purchase_order', 'payment_term', ['payment_term_id'], ['id'], source_schema='purchase', referent_schema='purchase', ondelete='SET NULL')
    op.add_column('vendor', sa.Column('payment_term_id', sa.BigInteger(), nullable=True), schema='purchase')
    op.add_column('vendor', sa.Column('lead_time_days', sa.Integer(), nullable=False), schema='purchase')
    op.add_column('vendor', sa.Column('wht_type', sa.String(length=10), nullable=False), schema='purchase')
    op.add_column('vendor', sa.Column('wht_rate', sa.Numeric(precision=5, scale=2), nullable=False), schema='purchase')
    op.add_column('vendor', sa.Column('performance_score', sa.Float(), nullable=False), schema='purchase')
    op.create_foreign_key(None, 'vendor', 'payment_term', ['payment_term_id'], ['id'], source_schema='purchase', referent_schema='purchase', ondelete='SET NULL')
    op.add_column('location', sa.Column('removal_strategy', sa.String(length=10), nullable=False), schema='wms')
    op.add_column('location', sa.Column('max_weight_kg', sa.Float(), nullable=True), schema='wms')
    op.add_column('location', sa.Column('max_volume_m3', sa.Float(), nullable=True), schema='wms')
    op.add_column('location', sa.Column('is_scrap', sa.Boolean(), nullable=False), schema='wms')
    op.add_column('location', sa.Column('sequence', sa.BigInteger(), nullable=False), schema='wms')
    op.add_column('lot', sa.Column('lot_type', sa.String(length=10), nullable=False), schema='wms')
    op.add_column('lot', sa.Column('use_date', sa.Date(), nullable=True), schema='wms')
    op.add_column('lot', sa.Column('removal_date', sa.Date(), nullable=True), schema='wms')
    op.add_column('lot', sa.Column('supplier_lot_ref', sa.String(length=60), nullable=True), schema='wms')
    op.alter_column('lot', 'note',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True,
               schema='wms')
    op.add_column('product', sa.Column('uom_purchase_id', sa.BigInteger(), nullable=True), schema='wms')
    op.add_column('product', sa.Column('tracking', sa.String(length=10), nullable=False), schema='wms')
    op.add_column('product', sa.Column('cost_method', sa.String(length=10), nullable=False), schema='wms')
    op.add_column('product', sa.Column('weight_kg', sa.Float(), nullable=False), schema='wms')
    op.add_column('product', sa.Column('volume_m3', sa.Float(), nullable=False), schema='wms')
    op.add_column('product', sa.Column('purchase_ok', sa.Boolean(), nullable=False), schema='wms')
    op.add_column('product', sa.Column('sale_ok', sa.Boolean(), nullable=False), schema='wms')
    op.add_column('product', sa.Column('avg_cost', sa.Numeric(precision=14, scale=6), nullable=False), schema='wms')
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True,
               schema='wms')
    op.create_foreign_key(None, 'product', 'uom', ['uom_purchase_id'], ['id'], source_schema='wms', referent_schema='wms', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', schema='wms', type_='foreignkey')
    op.alter_column('product', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True,
               schema='wms')
    op.drop_column('product', 'avg_cost', schema='wms')
    op.drop_column('product', 'sale_ok', schema='wms')
    op.drop_column('product', 'purchase_ok', schema='wms')
    op.drop_column('product', 'volume_m3', schema='wms')
    op.drop_column('product', 'weight_kg', schema='wms')
    op.drop_column('product', 'cost_method', schema='wms')
    op.drop_column('product', 'tracking', schema='wms')
    op.drop_column('product', 'uom_purchase_id', schema='wms')
    op.alter_column('lot', 'note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True,
               schema='wms')
    op.drop_column('lot', 'supplier_lot_ref', schema='wms')
    op.drop_column('lot', 'removal_date', schema='wms')
    op.drop_column('lot', 'use_date', schema='wms')
    op.drop_column('lot', 'lot_type', schema='wms')
    op.drop_column('location', 'sequence', schema='wms')
    op.drop_column('location', 'is_scrap', schema='wms')
    op.drop_column('location', 'max_volume_m3', schema='wms')
    op.drop_column('location', 'max_weight_kg', schema='wms')
    op.drop_column('location', 'removal_strategy', schema='wms')
    op.drop_constraint(None, 'vendor', schema='purchase', type_='foreignkey')
    op.drop_column('vendor', 'performance_score', schema='purchase')
    op.drop_column('vendor', 'wht_rate', schema='purchase')
    op.drop_column('vendor', 'wht_type', schema='purchase')
    op.drop_column('vendor', 'lead_time_days', schema='purchase')
    op.drop_column('vendor', 'payment_term_id', schema='purchase')
    op.drop_constraint(None, 'purchase_order', schema='purchase', type_='foreignkey')
    op.drop_constraint(None, 'purchase_order', schema='purchase', type_='foreignkey')
    op.drop_constraint(None, 'purchase_order', schema='purchase', type_='foreignkey')
    op.drop_constraint(None, 'purchase_order', schema='purchase', type_='foreignkey')
    op.drop_column('purchase_order', 'budget_id', schema='purchase')
    op.drop_column('purchase_order', 'approved_at', schema='purchase')
    op.drop_column('purchase_order', 'approver_id', schema='purchase')
    op.drop_column('purchase_order', 'approval_state', schema='purchase')
    op.drop_column('purchase_order', 'payment_term_id', schema='purchase')
    op.drop_column('purchase_order', 'buyer_id', schema='purchase')
    op.drop_column('purchase_order', 'incoterms', schema='purchase')
    op.drop_column('purchase_order', 'note_vendor', schema='purchase')
    op.drop_column('purchase_order', 'note_internal', schema='purchase')
    op.drop_constraint(None, 'po_line', schema='purchase', type_='foreignkey')
    op.drop_column('po_line', 'total', schema='purchase')
    op.drop_column('po_line', 'tax_amount', schema='purchase')
    op.drop_column('po_line', 'tax_rate', schema='purchase')
    op.drop_column('po_line', 'tax_id', schema='purchase')
    op.drop_constraint(None, 'work_order', schema='mfg', type_='foreignkey')
    op.drop_constraint(None, 'work_order', schema='mfg', type_='foreignkey')
    op.drop_column('work_order', 'shift_id', schema='mfg')
    op.drop_column('work_order', 'qty_production', schema='mfg')
    op.drop_column('work_order', 'remaining_minutes', schema='mfg')
    op.drop_column('work_order', 'setup_duration', schema='mfg')
    op.drop_column('work_order', 'planned_end', schema='mfg')
    op.drop_column('work_order', 'work_center_id', schema='mfg')
    op.drop_column('work_order', 'sequence', schema='mfg')
    op.drop_column('subcon_vendor', 'quality_score', schema='mfg')
    op.drop_column('subcon_vendor', 'variance_rate', schema='mfg')
    op.drop_constraint(None, 'manufacturing_order', schema='mfg', type_='foreignkey')
    op.drop_constraint(None, 'manufacturing_order', schema='mfg', type_='foreignkey')
    op.drop_column('manufacturing_order', 'subcon_recon_id', schema='mfg')
    op.drop_column('manufacturing_order', 'total_cost', schema='mfg')
    op.drop_column('manufacturing_order', 'overhead_cost', schema='mfg')
    op.drop_column('manufacturing_order', 'labor_cost', schema='mfg')
    op.drop_column('manufacturing_order', 'material_cost', schema='mfg')
    op.drop_column('manufacturing_order', 'lot_id', schema='mfg')
    op.drop_column('manufacturing_order', 'scheduled_end', schema='mfg')
    op.drop_column('manufacturing_order', 'scheduled_start', schema='mfg')
    op.drop_column('manufacturing_order', 'qty_scrap', schema='mfg')
    op.drop_constraint(None, 'bom_template', schema='mfg', type_='foreignkey')
    op.drop_column('bom_template', 'routing_id', schema='mfg')
    op.drop_column('bom_template', 'effective_to', schema='mfg')
    op.drop_column('bom_template', 'effective_from', schema='mfg')
    op.drop_column('bom_template', 'version', schema='mfg')
    op.drop_column('bom_line', 'hs_code', schema='mfg')
    op.drop_column('bom_line', 'country_of_origin', schema='mfg')
    op.drop_column('bom_line', 'sequence', schema='mfg')
    op.drop_column('bom_line', 'line_type', schema='mfg')
    op.drop_constraint(None, 'transfer_line', schema='inventory', type_='foreignkey')
    op.drop_constraint(None, 'transfer_line', schema='inventory', type_='foreignkey')
    op.drop_column('transfer_line', 'result_package_id', schema='inventory')
    op.drop_column('transfer_line', 'package_id', schema='inventory')
    op.drop_column('transfer_line', 'quantity_reserved', schema='inventory')
    op.drop_constraint(None, 'transfer', schema='inventory', type_='foreignkey')
    op.drop_constraint(None, 'transfer', schema='inventory', type_='foreignkey')
    op.drop_constraint(None, 'transfer', schema='inventory', type_='foreignkey')
    op.drop_constraint(None, 'transfer', schema='inventory', type_='foreignkey')
    op.alter_column('transfer', 'note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True,
               schema='inventory')
    op.drop_column('transfer', 'carrier_tracking_ref', schema='inventory')
    op.drop_column('transfer', 'carrier_id', schema='inventory')
    op.drop_column('transfer', 'responsible_id', schema='inventory')
    op.drop_column('transfer', 'backorder_id', schema='inventory')
    op.drop_column('transfer', 'origin_transfer_id', schema='inventory')
    op.drop_column('transfer', 'is_return', schema='inventory')
    op.drop_index(op.f('ix_inventory_stock_valuation_layer_product_id'), table_name='stock_valuation_layer', schema='inventory')
    op.drop_table('stock_valuation_layer', schema='inventory')
    op.drop_table('unbuild_order', schema='mfg')
    op.drop_index(op.f('ix_mfg_mo_scrap_mo_id'), table_name='mo_scrap', schema='mfg')
    op.drop_table('mo_scrap', schema='mfg')
    op.drop_index(op.f('ix_mfg_mo_production_signal_product_id'), table_name='mo_production_signal', schema='mfg')
    op.drop_table('mo_production_signal', schema='mfg')
    op.drop_index(op.f('ix_mfg_mo_component_line_mo_id'), table_name='mo_component_line', schema='mfg')
    op.drop_table('mo_component_line', schema='mfg')
    op.drop_table('batch_consolidation_item', schema='mfg')
    op.drop_table('landed_cost_transfer', schema='inventory')
    op.drop_index(op.f('ix_mfg_bom_version_bom_id'), table_name='bom_version', schema='mfg')
    op.drop_table('bom_version', schema='mfg')
    op.drop_table('scrap_order', schema='inventory')
    op.drop_index(op.f('ix_purchase_wht_certificate_purchase_order_id'), table_name='wht_certificate', schema='purchase')
    op.drop_table('wht_certificate', schema='purchase')
    op.drop_index(op.f('ix_purchase_supplier_pricelist_vendor_id'), table_name='supplier_pricelist', schema='purchase')
    op.drop_index(op.f('ix_purchase_supplier_pricelist_product_id'), table_name='supplier_pricelist', schema='purchase')
    op.drop_table('supplier_pricelist', schema='purchase')
    op.drop_index(op.f('ix_purchase_purchase_bill_purchase_order_id'), table_name='purchase_bill', schema='purchase')
    op.drop_table('purchase_bill', schema='purchase')
    op.drop_table('po_consolidation_item', schema='purchase')
    op.drop_index(op.f('ix_purchase_demand_signal_product_id'), table_name='demand_signal', schema='purchase')
    op.drop_table('demand_signal', schema='purchase')
    op.drop_index(op.f('ix_mfg_batch_consolidation_product_id'), table_name='batch_consolidation', schema='mfg')
    op.drop_table('batch_consolidation', schema='mfg')
    op.drop_table('reorder_rule', schema='inventory')
    op.drop_index(op.f('ix_inventory_putaway_rule_location_id'), table_name='putaway_rule', schema='inventory')
    op.drop_table('putaway_rule', schema='inventory')
    op.drop_table('package', schema='inventory')
    op.drop_table('landed_cost_line', schema='inventory')
    op.drop_index(op.f('ix_purchase_vendor_performance_vendor_id'), table_name='vendor_performance', schema='purchase')
    op.drop_table('vendor_performance', schema='purchase')
    op.drop_index(op.f('ix_purchase_vendor_document_vendor_id'), table_name='vendor_document', schema='purchase')
    op.drop_index(op.f('ix_purchase_vendor_document_expiry_date'), table_name='vendor_document', schema='purchase')
    op.drop_table('vendor_document', schema='purchase')
    op.drop_index(op.f('ix_purchase_po_consolidation_proposal_vendor_id'), table_name='po_consolidation_proposal', schema='purchase')
    op.drop_table('po_consolidation_proposal', schema='purchase')
    op.drop_index(op.f('ix_mfg_work_center_oee_work_center_id'), table_name='work_center_oee', schema='mfg')
    op.drop_table('work_center_oee', schema='mfg')
    op.drop_index(op.f('ix_mfg_routing_operation_routing_id'), table_name='routing_operation', schema='mfg')
    op.drop_table('routing_operation', schema='mfg')
    op.drop_table('landed_cost', schema='inventory')
    op.drop_table('payment_term_line', schema='purchase')
    op.drop_table('work_center', schema='mfg')
    op.drop_table('production_shift', schema='mfg')
    op.drop_index(op.f('ix_purchase_procurement_budget_project_code'), table_name='procurement_budget', schema='purchase')
    op.drop_table('procurement_budget', schema='purchase')
    op.drop_table('payment_term', schema='purchase')
    op.drop_table('routing', schema='mfg')
    op.drop_table('package_type', schema='inventory')
    # ### end Alembic commands ###
