[options]
admin_passwd = kob-master
db_host = odoo-postgres
db_port = 5432
db_user = odoo
db_password = 7pkRZPv0gzEdgnd6pcMvps7UhID5ZZK

; Odoo 19 stock addons + our KOB custom addons
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Performance / sizing for SME workloads
workers = 2
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

; Logging
log_level = info
log_handler = :INFO

; Network
proxy_mode = True
xmlrpc_port = 8069
longpolling_port = 8072

; Locale defaults — Thai
list_db = True
without_demo = False
